---
- name: "ensure cloudflare credentials"
  ansible.builtin.fail:
    msg: "Please make sure that cloudflare_zone account_email and account_api_key or api_token is defined!"
  when: "(cloudflare_zone_account_email | length and not cloudflare_zone_account_api_key and cloudflare_zone_api_token | length) or
         (not cloudflare_zone_account_email and cloudflare_zone_account_api_key | length and cloudflare_zone_api_token | length) or
         (cloudflare_zone_account_email | length and cloudflare_zone_account_api_key | length and cloudflare_zone_api_token | length)"

- name: "ensure cloudflare credentials"
  ansible.builtin.fail:
    msg: "Please make sure that cloudflare_zone account_name is defiend!"
  when: "not cloudflare_zone_account_name"

- name: "set cloudflare X-Auth-Email and X-Auth-Key headers"
  ansible.builtin.set_fact:
    cloudflare_zone_headers:
      X-Auth-Email: "{{ cloudflare_zone_account_email }}"
      X-Auth-Key: "{{ cloudflare_zone_account_api_key }}"
  when:
    - "cloudflare_zone_account_email | length"
    - "cloudflare_zone_account_api_key | length"

- name: "set cloudflare Authorization headers"
  ansible.builtin.set_fact:
    cloudflare_zone_headers:
      Authorization: "Bearer {{ cloudflare_zone_api_token }}"
  when: "cloudflare_zone_api_token | length"

- name: "get cloudflare account info"
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/accounts"
    method: "GET"
    headers: "{{ cloudflare_zone_headers }}"
    body_format: "json"
  register: "cloudflare_account_info"

- name: "set cloudflare account {{ cloudflare_zone_account_name }} id"
  ansible.builtin.set_fact:
    cloudflare_account_id: "{{ cloudflare_account_info.json.result | selectattr('name', 'eq', cloudflare_zone_account_name) | map(attribute='id') | first }}"

- name: "get cloudflare zone {{ cloudflare_zone_name }} info"
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones?name={{ cloudflare_zone_name }}"
    method: "GET"
    headers: "{{ cloudflare_zone_headers }}"
    body_format: "json"
  register: "cloudflare_zone_info"

- name: "set cloudflare zone {{ cloudflare_zone_name }} id"
  ansible.builtin.set_fact:
    cloudflare_zone_id: "{{ cloudflare_zone_info.json.result | map(attribute='id') | first }}"
  when: "cloudflare_zone_info.json.result | length"

- name: "create cloudflare zone {{ cloudflare_zone_name }}"
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones"
    method: "POST"
    headers: "{{ cloudflare_zone_headers }}"
    body_format: "json"
    body:
      name: "{{ cloudflare_zone_name }}"
      account:
        id: "{{ cloudflare_account_id }}"
      jump_start: "{{ cloudflare_zone_jump_start }}"
      type: "{{ cloudflare_zone_type }}"
  when: "not cloudflare_zone_info.json.result"
