---
namespace: "damex"
name: "cloudflare"
version: "0.2.13"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <damex.pp@icloud.com>"
license_file: "LICENSE"
tags:
  - "cloudflare"
repository: "https://github.com/damex/ansible-collections-cloudflare"
dependencies:
  "community.general": "*"
  "community.crypto": "*"
