---
- name: "ensure cloudflare acme domains"
  include_tasks: "cloudflare_acme_domain_certificates.yml"
  vars:
    cloudflare_acme_domain_name: "{{ cloudflare_acme_domain.name | mandatory }}"
    cloudflare_acme_domain_zone: "{{ cloudflare_acme_domain.zone | mandatory }}"
    cloudflare_acme_domain_account_email: "{{ cloudflare_acme_domain.account_email | default(cloudflare_acme_account_email) }}"
    cloudflare_acme_domain_cloudflare_account_email: "{{ cloudflare_acme_domain.cloudflare_account_email | default(cloudflare_acme_cloudflare_account_email) }}"
    cloudflare_acme_domain_cloudflare_account_api_key: "{{ cloudflare_acme_domain.cloudflare_account_api_key | default(cloudflare_acme_cloudflare_account_api_key) }}"
    cloudflare_acme_domain_cloudflare_api_token: "{{ cloudflare_acme_domain.cloudflare_api_token | default(cloudflare_acme_cloudflare_api_token) }}"
  loop: "{{ cloudflare_acme_domains }}"
  loop_control:
    loop_var: "cloudflare_acme_domain"
